apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
      - name: flask-app
        image: techpertz/myflaskapp:latest
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          timeoutSeconds: 2
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          timeoutSeconds: 2
          periodSeconds: 5
          successThreshold: 1
        env:
        - name: MONGO_HOST
          value: "mongodb"
        - name: MONGO_PORT
          value: "27017"


# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-app
# spec:
#   replicas: 4  
#   selector:
#     matchLabels:
#       app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#       - name: flask-app
#         image: techpertz/myflaskapp:v2  
#         ports:
#         - containerPort: 5000
#         env:
#         - name: MONGO_HOST
#           value: "mongodb"
#         - name: MONGO_PORT
#           value: "27017"
#   strategy:
#     type: RollingUpdate
#     rollingUpdate:
#       maxUnavailable: 1
#       maxSurge: 1
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app
# spec:
#   type: NodePort
#   ports:
#   - port: 5000
#     targetPort: 5000
#     nodePort: 30001  
#   selector:
#     app: flask-app



# ------------------------




# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: flask-app
# spec:
#   replicas: 2  
#   selector:
#     matchLabels:
#       app: flask-app
#   template:
#     metadata:
#       labels:
#         app: flask-app
#     spec:
#       containers:
#       - name: flask-app
#         image: techpertz/myflaskapp:latest
#         ports:
#         - containerPort: 5000
#         env:
#         - name: MONGO_HOST
#           value: "mongodb"
#         - name: MONGO_PORT
#           value: "27017"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: flask-app
# spec:
#   type: NodePort
#   ports:
#   - port: 5000
#     targetPort: 5000
#     nodePort: 30001
#   selector:
#     app: flask-app
